version: 2
jobs:
  # Define a "build_docs" job to be run with Circle
  build_docs:
    # This is the base environment that Circle will use
    docker:
      - image: circleci/python:3.6-stretch
    steps:
      # Get our data and merge with upstream
      - run: sudo apt-get update
      - checkout
      # Update our path
      - run: echo "export PATH=~/.local/bin:$PATH" >> $BASH_ENV
      # Restore cached files to speed things up
      - restore_cache:
          keys:
            - cache-pip
      # Install the packages needed to build our documentation
      # This will depend on your particular package!
      - run:
          name: Set up environment
          command: |
            # Install conda
            wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
            bash miniconda.sh -b -p $HOME/miniconda
            export PATH="$HOME/miniconda/bin:$PATH"
            conda config --set always_yes yes --set changeps1 no
            conda update conda
            conda config --add channels conda-forge
            conda install yarn
            yarn && yarn build
            # Install pandas + some optional dependencies
            pip install -r docs/requirements.txt
            # install the theme package
            pip install -e .
      # Cache some files for a speedup in subsequent builds
      - save_cache:
          key: cache-pip
          paths:
            - ~/.cache/pip
      # Build the docs
      - run:
          name: Build docs to store
          command: |
            export PATH="$HOME/miniconda/bin:$PATH"
            sphinx-build -b html docs/ docs/_build/html -W --keep-going

      # Tell Circle to store the documentation output in a folder that we can access later
      - store_artifacts:
          path: docs/_build/html/
          destination: html

# Tell CircleCI to use this workflow when it builds the site
workflows:
  version: 2
  default:
    jobs:
      - build_docs
