on: [status]
jobs:
  circleci_artifacts_redirector_job:
    runs-on: ubuntu-latest
    name: Run CircleCI artifacts redirector
    steps:
      - name: Create URL for CircleCI artifact
        id: redirect
        uses: larsoner/circleci-artifacts-redirector-action@0.2.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          artifact-path: 0/html/index.html
      - name: Wait Until Site is Ready
        run: |
          curl --retry-all-errors --retry-max-time 60 ${{ steps.redirect.outputs.url }}
      - name: Run Lighthouse on Site
        id: lighthouse
        uses: foo-software/lighthouse-check-action@v2.0.0
        with:
          urls: ${{ steps.redirect.outputs.url }}
          outputDirectory: /tmp/lighthouse
          verbose: true
      - name: Upload Lighthouse Reports
        uses: actions/upload-artifact@v2
        with:
          name: Lighthouse Report ${{ github.run_number }}
          path: /tmp/lighthouse
